{
 "title": "Ethminer",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ethminer_hashrate", "legendFormat": "Mh/s" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ethminer_gpu_temp", "legendFormat": "℃" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ethminer_gpu_power", "legendFormat": "Watts" }
   ]
  }
 ]
}